/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Skafform API
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod/mini";

/**
 * @summary Liveness probe
 */
export const GetHealthResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.enum(["ok"]),
});

/**
 * @summary Les organizations de l'utilisateur
 */
export const GetApiOrganizationsResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
});
export const GetApiOrganizationsResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsResponseItem,
);

/**
 * @summary Créer une organization
 */
export const postApiOrganizationsBodyNameMax = 200;

export const PostApiOrganizationsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(/*#__PURE__*/ zod.maxLength(postApiOrganizationsBodyNameMax)),
});

export const PostApiOrganizationsResponse = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
});

/**
 * @summary Les projets d'une organization
 */
export const GetApiOrganizationsOrganizationIdProjectsParams = /*#__PURE__*/ zod.object(
  {
    organizationId: /*#__PURE__*/ zod.uuid(),
  },
);

export const GetApiOrganizationsOrganizationIdProjectsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
  });
export const GetApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdProjectsResponseItem);

/**
 * @summary Créer un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsBodyNameMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(
      /*#__PURE__*/ zod.maxLength(
        postApiOrganizationsOrganizationIdProjectsBodyNameMax,
      ),
    ),
});

export const PostApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      id: /*#__PURE__*/ zod.uuid(),
      name: /*#__PURE__*/ zod.string(),
    }),
    /*#__PURE__*/ zod.object({
      createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    }),
  );

/**
 * @summary Les permissions de l'acteur dans un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeResponse =
  /*#__PURE__*/ zod.object({
    permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  });

/**
 * @summary Les membres d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem,
  );

/**
 * @summary Le rôle et les permissions de l'acteur
 */
export const GetApiOrganizationsOrganizationIdMeParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMeResponse = /*#__PURE__*/ zod.object({
  permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
});

/**
 * @summary Les membres d'une organization
 */
export const GetApiOrganizationsOrganizationIdMembersParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdMembersResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdMembersResponseItem,
);

/**
 * @summary Les rôles d'une organization
 */
export const GetApiOrganizationsOrganizationIdRolesParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdRolesResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    scope: /*#__PURE__*/ zod.enum(["organization", "project"]),
    isSystem: /*#__PURE__*/ zod.boolean(),
    assignable: /*#__PURE__*/ zod.boolean(),
  });
export const GetApiOrganizationsOrganizationIdRolesResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdRolesResponseItem,
);

/**
 * @summary Les invitations en attente
 */
export const GetApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdInvitationsResponseItem);

/**
 * @summary Inviter quelqu'un
 */
export const PostApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Les invitations en attente sur un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem,
  );

/**
 * @summary Inviter quelqu'un sur un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Annuler une invitation
 */
export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    invitationId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Décrire une invitation
 */

export const GetApiInvitationsTokenParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const GetApiInvitationsTokenResponse = /*#__PURE__*/ zod.object({
  email: /*#__PURE__*/ zod.email(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  hasAccount: /*#__PURE__*/ zod.boolean(),
});

/**
 * @summary Accepter une invitation
 */

export const PostApiInvitationsTokenAcceptParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const PostApiInvitationsTokenAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});

/**
 * @summary Les invitations reçues
 */
export const GetApiInboxResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
});
export const GetApiInboxResponse = /*#__PURE__*/ zod.array(GetApiInboxResponseItem);

/**
 * @summary Accepter une invitation reçue
 */
export const PostApiInboxInvitationIdAcceptParams = /*#__PURE__*/ zod.object({
  invitationId: /*#__PURE__*/ zod.uuid(),
});

export const PostApiInboxInvitationIdAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});
