/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Skafform API
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod/mini";

/**
 * @summary Liveness probe
 */
export const GetHealthResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.enum(["ok"]),
});

/**
 * @summary Les fournisseurs OAuth configurés
 */
export const GetApiAuthProvidersResponse = /*#__PURE__*/ zod.object({
  providers: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
});

/**
 * @summary Les organizations de l'utilisateur
 */
export const GetApiOrganizationsResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
  description: /*#__PURE__*/ zod.string(),
});
export const GetApiOrganizationsResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsResponseItem,
);

/**
 * @summary Créer une organization
 */
export const postApiOrganizationsBodyNameMax = 200;

export const PostApiOrganizationsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(/*#__PURE__*/ zod.maxLength(postApiOrganizationsBodyNameMax)),
});

export const PostApiOrganizationsResponse = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
  description: /*#__PURE__*/ zod.string(),
});

/**
 * @summary Les projets d'une organization
 */
export const GetApiOrganizationsOrganizationIdProjectsParams = /*#__PURE__*/ zod.object(
  {
    organizationId: /*#__PURE__*/ zod.uuid(),
  },
);

export const GetApiOrganizationsOrganizationIdProjectsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    description: /*#__PURE__*/ zod.string(),
  });
export const GetApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdProjectsResponseItem);

/**
 * @summary Créer un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsBodyNameMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(
      /*#__PURE__*/ zod.maxLength(
        postApiOrganizationsOrganizationIdProjectsBodyNameMax,
      ),
    ),
});

export const PostApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    description: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Réglages d'une organization
 */
export const PutApiOrganizationsOrganizationIdParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const putApiOrganizationsOrganizationIdBodyOneNameMax = 200;

export const putApiOrganizationsOrganizationIdBodyOneDescriptionMax = 1000;

export const putApiOrganizationsOrganizationIdBodyTwoBillingAddressMax = 500;

export const PutApiOrganizationsOrganizationIdBody = /*#__PURE__*/ zod.intersection(
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(putApiOrganizationsOrganizationIdBodyOneNameMax),
      ),
    description: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdBodyOneDescriptionMax,
        ),
      ),
  }),
  /*#__PURE__*/ zod.object({
    billingAddress: /*#__PURE__*/ zod.nullish(
      /*#__PURE__*/ zod
        .string()
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdBodyTwoBillingAddressMax,
          ),
        ),
    ),
  }),
);

export const PutApiOrganizationsOrganizationIdResponse = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
  description: /*#__PURE__*/ zod.string(),
});

/**
 * @summary Supprimer une organization vidée
 */
export const DeleteApiOrganizationsOrganizationIdParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const DeleteApiOrganizationsOrganizationIdResponse = /*#__PURE__*/ zod.void();

/**
 * @summary L'adresse de facturation
 */
export const GetApiOrganizationsOrganizationIdBillingParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdBillingResponse =
  /*#__PURE__*/ zod.object({
    billingAddress: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  });

/**
 * @summary Réglages d'un projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdProjectsProjectIdBodyNameMax = 200;

export const putApiOrganizationsOrganizationIdProjectsProjectIdBodyDescriptionMax = 1000;

export const PutApiOrganizationsOrganizationIdProjectsProjectIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdProjectsProjectIdBodyNameMax,
        ),
      ),
    description: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdProjectsProjectIdBodyDescriptionMax,
        ),
      ),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    description: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Supprimer un projet vidé
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      id: /*#__PURE__*/ zod.uuid(),
      name: /*#__PURE__*/ zod.string(),
      description: /*#__PURE__*/ zod.string(),
    }),
    /*#__PURE__*/ zod.object({
      createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    }),
  );

/**
 * @summary Les permissions de l'acteur dans un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeResponse =
  /*#__PURE__*/ zod.object({
    permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  });

/**
 * @summary Les membres d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    suspendedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
    manageable: /*#__PURE__*/ zod.boolean(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem,
  );

/**
 * @summary Le rôle et les permissions de l'acteur
 */
export const GetApiOrganizationsOrganizationIdMeParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMeResponse = /*#__PURE__*/ zod.object({
  permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
});

/**
 * @summary Les membres d'une organization
 */
export const GetApiOrganizationsOrganizationIdMembersParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    suspendedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
    manageable: /*#__PURE__*/ zod.boolean(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdMembersResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdMembersResponseItem,
);

/**
 * @summary Les rôles d'une organization
 */
export const GetApiOrganizationsOrganizationIdRolesParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdRolesResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    scope: /*#__PURE__*/ zod.enum(["organization", "project"]),
    isSystem: /*#__PURE__*/ zod.boolean(),
    assignable: /*#__PURE__*/ zod.boolean(),
    permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
    holders: /*#__PURE__*/ zod.int(),
  });
export const GetApiOrganizationsOrganizationIdRolesResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdRolesResponseItem,
);

/**
 * @summary Créer un rôle personnalisé
 */
export const PostApiOrganizationsOrganizationIdRolesParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const postApiOrganizationsOrganizationIdRolesBodyOneNameMax = 200;

export const PostApiOrganizationsOrganizationIdRolesBody =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      name: /*#__PURE__*/ zod
        .string()
        .check(/*#__PURE__*/ zod.minLength(1))
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdRolesBodyOneNameMax,
          ),
        ),
      permissions: /*#__PURE__*/ zod.array(
        /*#__PURE__*/ zod.enum([
          "member.read",
          "member.manage",
          "member.manage_admin",
          "role.manage",
          "apikey.manage",
          "project.create",
          "project.delete",
          "project.settings",
          "org.settings",
          "org.billing",
          "org.transfer",
          "org.delete",
          "content.read",
          "content.read_draft",
          "content.write",
          "content.publish",
          "schema.read",
          "schema.write",
          "library.write",
        ]),
      ),
    }),
    /*#__PURE__*/ zod.object({
      scope: /*#__PURE__*/ zod.enum(["organization", "project"]),
    }),
  );

export const PostApiOrganizationsOrganizationIdRolesResponse = /*#__PURE__*/ zod.object(
  {
    id: /*#__PURE__*/ zod.uuid(),
  },
);

/**
 * @summary Les invitations en attente
 */
export const GetApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdInvitationsResponseItem);

/**
 * @summary Inviter quelqu'un
 */
export const PostApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Le catalogue de permissions
 */
export const GetApiPermissionsResponseItem = /*#__PURE__*/ zod.object({
  key: /*#__PURE__*/ zod.string(),
  description: /*#__PURE__*/ zod.string(),
});
export const GetApiPermissionsResponse = /*#__PURE__*/ zod.array(
  GetApiPermissionsResponseItem,
);

/**
 * @summary Modifier un rôle personnalisé
 */
export const PutApiOrganizationsOrganizationIdRolesRoleIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdRolesRoleIdBodyNameMax = 200;

export const PutApiOrganizationsOrganizationIdRolesRoleIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdRolesRoleIdBodyNameMax,
        ),
      ),
    permissions: /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.enum([
        "member.read",
        "member.manage",
        "member.manage_admin",
        "role.manage",
        "apikey.manage",
        "project.create",
        "project.delete",
        "project.settings",
        "org.settings",
        "org.billing",
        "org.transfer",
        "org.delete",
        "content.read",
        "content.read_draft",
        "content.write",
        "content.publish",
        "schema.read",
        "schema.write",
        "library.write",
      ]),
    ),
  });

export const PutApiOrganizationsOrganizationIdRolesRoleIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Supprimer un rôle personnalisé
 */
export const DeleteApiOrganizationsOrganizationIdRolesRoleIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdRolesRoleIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Retirer un membre, ou quitter l'organization
 */
export const DeleteApiOrganizationsOrganizationIdMembersUserIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const DeleteApiOrganizationsOrganizationIdMembersUserIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Suspendre ou réactiver une adhésion
 */
export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionBody =
  /*#__PURE__*/ zod.object({
    suspended: /*#__PURE__*/ zod.boolean(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Changer le rôle d'un membre
 */
export const PutApiOrganizationsOrganizationIdMembersUserIdRoleParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdRoleBody =
  /*#__PURE__*/ zod.object({
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdRoleResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Retirer un membre d'un projet, ou le quitter
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Suspendre ou réactiver une adhésion à un projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionBody =
  /*#__PURE__*/ zod.object({
    suspended: /*#__PURE__*/ zod.boolean(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Changer le rôle d'un membre de projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleBody =
  /*#__PURE__*/ zod.object({
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Les clés API d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    kind: /*#__PURE__*/ zod.enum(["public", "preview", "secret"]),
    name: /*#__PURE__*/ zod.string(),
    token: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    hint: /*#__PURE__*/ zod.string(),
    revokedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponseItem,
  );

/**
 * @summary Créer une clé API
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBodyNameMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBody =
  /*#__PURE__*/ zod.object({
    kind: /*#__PURE__*/ zod.enum(["public", "preview", "secret"]),
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBodyNameMax,
        ),
      ),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    token: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Révoquer une clé API
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdRevokeParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    apiKeyId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdRevokeResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Supprimer une clé API révoquée
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    apiKeyId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Les invitations en attente sur un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem,
  );

/**
 * @summary Inviter quelqu'un sur un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Annuler une invitation
 */
export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    invitationId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Décrire une invitation
 */

export const GetApiInvitationsTokenParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const GetApiInvitationsTokenResponse = /*#__PURE__*/ zod.object({
  email: /*#__PURE__*/ zod.email(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  hasAccount: /*#__PURE__*/ zod.boolean(),
});

/**
 * @summary Accepter une invitation
 */

export const PostApiInvitationsTokenAcceptParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const PostApiInvitationsTokenAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});

/**
 * @summary Les invitations reçues
 */
export const GetApiInboxResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
});
export const GetApiInboxResponse = /*#__PURE__*/ zod.array(GetApiInboxResponseItem);

/**
 * @summary Accepter une invitation reçue
 */
export const PostApiInboxInvitationIdAcceptParams = /*#__PURE__*/ zod.object({
  invitationId: /*#__PURE__*/ zod.uuid(),
});

export const PostApiInboxInvitationIdAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});

/**
 * @summary Les types de contenu d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemNameMax = 64;

export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemLabelMax = 200;

export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemToMax = 64;

export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsMax = 200;

export const GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseItem =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      id: /*#__PURE__*/ zod.uuid(),
      name: /*#__PURE__*/ zod.string(),
      label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
      definition: /*#__PURE__*/ zod.object({
        fields: /*#__PURE__*/ zod
          .array(
            /*#__PURE__*/ zod.object({
              name: /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemNameMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemNameRegExp,
                  ),
                ),
              type: /*#__PURE__*/ zod.enum([
                "text",
                "longtext",
                "number",
                "boolean",
                "date",
                "reference",
              ]),
              label: /*#__PURE__*/ zod.optional(
                /*#__PURE__*/ zod
                  .string()
                  .check(/*#__PURE__*/ zod.minLength(1))
                  .check(
                    /*#__PURE__*/ zod.maxLength(
                      getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemLabelMax,
                    ),
                  ),
              ),
              to: /*#__PURE__*/ zod.optional(
                /*#__PURE__*/ zod
                  .string()
                  .check(
                    /*#__PURE__*/ zod.maxLength(
                      getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemToMax,
                    ),
                  )
                  .check(
                    /*#__PURE__*/ zod.regex(
                      getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsItemToRegExp,
                    ),
                  ),
              ),
              validation: /*#__PURE__*/ zod.object({
                required: /*#__PURE__*/ zod.boolean(),
              }),
            }),
          )
          .check(
            /*#__PURE__*/ zod.maxLength(
              getApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseOneDefinitionFieldsMax,
            ),
          ),
      }),
      createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
      updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    }),
    /*#__PURE__*/ zod.object({
      origin: /*#__PURE__*/ zod.nullable(
        /*#__PURE__*/ zod.object({
          librarySchemaId: /*#__PURE__*/ zod.uuid(),
          name: /*#__PURE__*/ zod.string(),
          state: /*#__PURE__*/ zod.enum([
            "identical",
            "library_ahead",
            "locally_modified",
          ]),
        }),
      ),
    }),
  );
export const GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseItem,
  );

/**
 * @summary Créer un type de contenu
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyNameMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyLabelMax = 200;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyNameMax,
        ),
      )
      .check(
        /*#__PURE__*/ zod.regex(
          postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyNameRegExp,
        ),
      ),
    label: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod
        .string()
        .check(/*#__PURE__*/ zod.minLength(1))
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyLabelMax,
          ),
        ),
    ),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdProjectsProjectIdSchemasBodyDefinitionFieldsMax,
          ),
        ),
    }),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdProjectsProjectIdSchemasResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Modifier un type de contenu
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyNameMax = 64;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyLabelMax = 200;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemNameMax = 64;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemLabelMax = 200;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemToMax = 64;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsMax = 200;

export const PutApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyNameMax,
        ),
      )
      .check(
        /*#__PURE__*/ zod.regex(
          putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyNameRegExp,
        ),
      ),
    label: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod
        .string()
        .check(/*#__PURE__*/ zod.minLength(1))
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyLabelMax,
          ),
        ),
    ),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdBodyDefinitionFieldsMax,
          ),
        ),
    }),
  });

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemNameMax = 64;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemLabelMax = 200;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemToMax = 64;

export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsMax = 200;

export const PutApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Supprimer un type de contenu
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary La lignée d'un type de contenu
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
  });

export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryResponseCurrentHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;
export const getApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryResponseEntriesItemHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;

export const GetApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryResponse =
  /*#__PURE__*/ zod.object({
    currentHash: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          getApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryResponseCurrentHashRegExp,
        ),
      ),
    entries: /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.object({
        hash: /*#__PURE__*/ zod
          .string()
          .check(
            /*#__PURE__*/ zod.regex(
              getApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdHistoryResponseEntriesItemHashRegExp,
            ),
          ),
        action: /*#__PURE__*/ zod.enum(["saved", "restored"]),
        createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
        actorName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
        actorEmail: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
        name: /*#__PURE__*/ zod.string(),
        label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
      }),
    ),
  });

/**
 * @summary Restaurer une version antérieure
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreBodyHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreBody =
  /*#__PURE__*/ zod.object({
    hash: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreBodyHashRegExp,
        ),
      ),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdProjectsProjectIdSchemasSchemaIdRestoreResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Copier un schéma de la bibliothèque dans ce projet
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyBody =
  /*#__PURE__*/ zod.object({
    librarySchemaId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdProjectsProjectIdSchemasCopyResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Les schémas de la bibliothèque
 */
export const GetApiOrganizationsOrganizationIdLibraryParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemNameMax = 64;

export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemLabelMax = 200;

export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemToMax = 64;

export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsMax = 200;

export const getApiOrganizationsOrganizationIdLibraryResponseTwoCurrentHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;

export const GetApiOrganizationsOrganizationIdLibraryResponseItem =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      id: /*#__PURE__*/ zod.uuid(),
      name: /*#__PURE__*/ zod.string(),
      label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
      definition: /*#__PURE__*/ zod.object({
        fields: /*#__PURE__*/ zod
          .array(
            /*#__PURE__*/ zod.object({
              name: /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemNameMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemNameRegExp,
                  ),
                ),
              type: /*#__PURE__*/ zod.enum([
                "text",
                "longtext",
                "number",
                "boolean",
                "date",
                "reference",
              ]),
              label: /*#__PURE__*/ zod.optional(
                /*#__PURE__*/ zod
                  .string()
                  .check(/*#__PURE__*/ zod.minLength(1))
                  .check(
                    /*#__PURE__*/ zod.maxLength(
                      getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemLabelMax,
                    ),
                  ),
              ),
              to: /*#__PURE__*/ zod.optional(
                /*#__PURE__*/ zod
                  .string()
                  .check(
                    /*#__PURE__*/ zod.maxLength(
                      getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemToMax,
                    ),
                  )
                  .check(
                    /*#__PURE__*/ zod.regex(
                      getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsItemToRegExp,
                    ),
                  ),
              ),
              validation: /*#__PURE__*/ zod.object({
                required: /*#__PURE__*/ zod.boolean(),
              }),
            }),
          )
          .check(
            /*#__PURE__*/ zod.maxLength(
              getApiOrganizationsOrganizationIdLibraryResponseOneDefinitionFieldsMax,
            ),
          ),
      }),
      createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
      updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    }),
    /*#__PURE__*/ zod.object({
      currentHash: /*#__PURE__*/ zod
        .string()
        .check(
          /*#__PURE__*/ zod.regex(
            getApiOrganizationsOrganizationIdLibraryResponseTwoCurrentHashRegExp,
          ),
        ),
    }),
  );
export const GetApiOrganizationsOrganizationIdLibraryResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdLibraryResponseItem,
);

/**
 * @summary Ajouter un schéma à la bibliothèque
 */
export const PostApiOrganizationsOrganizationIdLibraryParams = /*#__PURE__*/ zod.object(
  {
    organizationId: /*#__PURE__*/ zod.uuid(),
  },
);

export const postApiOrganizationsOrganizationIdLibraryBodyNameMax = 64;

export const postApiOrganizationsOrganizationIdLibraryBodyNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryBodyLabelMax = 200;

export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdLibraryBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(
      /*#__PURE__*/ zod.maxLength(postApiOrganizationsOrganizationIdLibraryBodyNameMax),
    )
    .check(
      /*#__PURE__*/ zod.regex(postApiOrganizationsOrganizationIdLibraryBodyNameRegExp),
    ),
  label: /*#__PURE__*/ zod.nullable(
    /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdLibraryBodyLabelMax,
        ),
      ),
  ),
  definition: /*#__PURE__*/ zod.object({
    fields: /*#__PURE__*/ zod
      .array(
        /*#__PURE__*/ zod.object({
          name: /*#__PURE__*/ zod
            .string()
            .check(
              /*#__PURE__*/ zod.maxLength(
                postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemNameMax,
              ),
            )
            .check(
              /*#__PURE__*/ zod.regex(
                postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemNameRegExp,
              ),
            ),
          type: /*#__PURE__*/ zod.enum([
            "text",
            "longtext",
            "number",
            "boolean",
            "date",
            "reference",
          ]),
          label: /*#__PURE__*/ zod.optional(
            /*#__PURE__*/ zod
              .string()
              .check(/*#__PURE__*/ zod.minLength(1))
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemLabelMax,
                ),
              ),
          ),
          to: /*#__PURE__*/ zod.optional(
            /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemToMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsItemToRegExp,
                ),
              ),
          ),
          validation: /*#__PURE__*/ zod.object({
            required: /*#__PURE__*/ zod.boolean(),
          }),
        }),
      )
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdLibraryBodyDefinitionFieldsMax,
        ),
      ),
  }),
});

export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdLibraryResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdLibraryResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Modifier un schéma de la bibliothèque
 */
export const PutApiOrganizationsOrganizationIdLibraryLibrarySchemaIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    librarySchemaId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyNameMax = 64;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyLabelMax = 200;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemNameMax = 64;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemLabelMax = 200;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemToMax = 64;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsMax = 200;

export const PutApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyNameMax,
        ),
      )
      .check(
        /*#__PURE__*/ zod.regex(
          putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyNameRegExp,
        ),
      ),
    label: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod
        .string()
        .check(/*#__PURE__*/ zod.minLength(1))
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyLabelMax,
          ),
        ),
    ),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdBodyDefinitionFieldsMax,
          ),
        ),
    }),
  });

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemNameMax = 64;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemLabelMax = 200;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemToMax = 64;

export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsMax = 200;

export const PutApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            putApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Retirer un schéma de la bibliothèque
 */
export const DeleteApiOrganizationsOrganizationIdLibraryLibrarySchemaIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    librarySchemaId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdLibraryLibrarySchemaIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary La lignée d'un schéma de bibliothèque
 */
export const GetApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    librarySchemaId: /*#__PURE__*/ zod.uuid(),
  });

export const getApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryResponseCurrentHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;
export const getApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryResponseEntriesItemHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;

export const GetApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryResponse =
  /*#__PURE__*/ zod.object({
    currentHash: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          getApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryResponseCurrentHashRegExp,
        ),
      ),
    entries: /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.object({
        hash: /*#__PURE__*/ zod
          .string()
          .check(
            /*#__PURE__*/ zod.regex(
              getApiOrganizationsOrganizationIdLibraryLibrarySchemaIdHistoryResponseEntriesItemHashRegExp,
            ),
          ),
        action: /*#__PURE__*/ zod.enum(["saved", "restored"]),
        createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
        actorName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
        actorEmail: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
        name: /*#__PURE__*/ zod.string(),
        label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
      }),
    ),
  });

/**
 * @summary Restaurer une version antérieure d'un schéma de bibliothèque
 */
export const PostApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    librarySchemaId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreBodyHashRegExp =
  /^[a-z0-9-]+:[0-9a-f]{64}$/;

export const PostApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreBody =
  /*#__PURE__*/ zod.object({
    hash: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreBodyHashRegExp,
        ),
      ),
  });

export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemNameMax = 64;

export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemNameRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemLabelMax = 200;

export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemToMax = 64;

export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemToRegExp =
  /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsMax = 200;

export const PostApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    label: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    definition: /*#__PURE__*/ zod.object({
      fields: /*#__PURE__*/ zod
        .array(
          /*#__PURE__*/ zod.object({
            name: /*#__PURE__*/ zod
              .string()
              .check(
                /*#__PURE__*/ zod.maxLength(
                  postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemNameMax,
                ),
              )
              .check(
                /*#__PURE__*/ zod.regex(
                  postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemNameRegExp,
                ),
              ),
            type: /*#__PURE__*/ zod.enum([
              "text",
              "longtext",
              "number",
              "boolean",
              "date",
              "reference",
            ]),
            label: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(/*#__PURE__*/ zod.minLength(1))
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemLabelMax,
                  ),
                ),
            ),
            to: /*#__PURE__*/ zod.optional(
              /*#__PURE__*/ zod
                .string()
                .check(
                  /*#__PURE__*/ zod.maxLength(
                    postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemToMax,
                  ),
                )
                .check(
                  /*#__PURE__*/ zod.regex(
                    postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsItemToRegExp,
                  ),
                ),
            ),
            validation: /*#__PURE__*/ zod.object({
              required: /*#__PURE__*/ zod.boolean(),
            }),
          }),
        )
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdLibraryLibrarySchemaIdRestoreResponseDefinitionFieldsMax,
          ),
        ),
    }),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Les entries d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdDocumentsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdDocumentsQueryParams =
  /*#__PURE__*/ zod.object({
    schemaId: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.uuid()),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdDocumentsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdDocumentsResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdDocumentsResponseItem,
  );

/**
 * @summary Créer une entry
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsBody =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      data: /*#__PURE__*/ zod.record(
        /*#__PURE__*/ zod.string(),
        /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
      ),
    }),
    /*#__PURE__*/ zod.object({
      schemaId: /*#__PURE__*/ zod.uuid(),
    }),
  );

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Enregistrer une entry
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    documentId: /*#__PURE__*/ zod.uuid(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdBody =
  /*#__PURE__*/ zod.object({
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });

/**
 * @summary Supprimer une entry
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    documentId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Publier des entries
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishBodyDocumentIdsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishBody =
  /*#__PURE__*/ zod.object({
    documentIds: /*#__PURE__*/ zod
      .array(/*#__PURE__*/ zod.uuid())
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishBodyDocumentIdsMax,
        ),
      ),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishResponse =
  /*#__PURE__*/ zod.array(
    PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsPublishResponseItem,
  );

/**
 * @summary Dépublier des entries
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishBodyDocumentIdsMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishBody =
  /*#__PURE__*/ zod.object({
    documentIds: /*#__PURE__*/ zod
      .array(/*#__PURE__*/ zod.uuid())
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishBodyDocumentIdsMax,
        ),
      ),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishResponse =
  /*#__PURE__*/ zod.array(
    PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsUnpublishResponseItem,
  );

/**
 * @summary Abandonner les modifications d'une entry
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdDiscardParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    documentId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdDocumentsDocumentIdDiscardResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    schemaId: /*#__PURE__*/ zod.uuid(),
    data: /*#__PURE__*/ zod.record(
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.unknown()),
    ),
    state: /*#__PURE__*/ zod.enum(["draft", "published", "changed"]),
    createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    updatedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
