/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Skafform API
 * OpenAPI spec version: 0.0.0
 */
import * as zod from "zod/mini";

/**
 * @summary Liveness probe
 */
export const GetHealthResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.enum(["ok"]),
});

/**
 * @summary Les fournisseurs OAuth configurés
 */
export const GetApiAuthProvidersResponse = /*#__PURE__*/ zod.object({
  providers: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
});

/**
 * @summary Les organizations de l'utilisateur
 */
export const GetApiOrganizationsResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
});
export const GetApiOrganizationsResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsResponseItem,
);

/**
 * @summary Créer une organization
 */
export const postApiOrganizationsBodyNameMax = 200;

export const PostApiOrganizationsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(/*#__PURE__*/ zod.maxLength(postApiOrganizationsBodyNameMax)),
});

export const PostApiOrganizationsResponse = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
});

/**
 * @summary Les projets d'une organization
 */
export const GetApiOrganizationsOrganizationIdProjectsParams = /*#__PURE__*/ zod.object(
  {
    organizationId: /*#__PURE__*/ zod.uuid(),
  },
);

export const GetApiOrganizationsOrganizationIdProjectsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
  });
export const GetApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdProjectsResponseItem);

/**
 * @summary Créer un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsBodyNameMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(
      /*#__PURE__*/ zod.maxLength(
        postApiOrganizationsOrganizationIdProjectsBodyNameMax,
      ),
    ),
});

export const PostApiOrganizationsOrganizationIdProjectsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Renommer une organization
 */
export const PutApiOrganizationsOrganizationIdParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const putApiOrganizationsOrganizationIdBodyNameMax = 200;

export const PutApiOrganizationsOrganizationIdBody = /*#__PURE__*/ zod.object({
  name: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1))
    .check(/*#__PURE__*/ zod.maxLength(putApiOrganizationsOrganizationIdBodyNameMax)),
});

export const PutApiOrganizationsOrganizationIdResponse = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  name: /*#__PURE__*/ zod.string(),
});

/**
 * @summary Supprimer une organization vidée
 */
export const DeleteApiOrganizationsOrganizationIdParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const DeleteApiOrganizationsOrganizationIdResponse = /*#__PURE__*/ zod.void();

/**
 * @summary Renommer un projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdProjectsProjectIdBodyNameMax = 200;

export const PutApiOrganizationsOrganizationIdProjectsProjectIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdProjectsProjectIdBodyNameMax,
        ),
      ),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Supprimer un projet vidé
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdResponse =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      id: /*#__PURE__*/ zod.uuid(),
      name: /*#__PURE__*/ zod.string(),
    }),
    /*#__PURE__*/ zod.object({
      createdAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    }),
  );

/**
 * @summary Les permissions de l'acteur dans un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMeResponse =
  /*#__PURE__*/ zod.object({
    permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  });

/**
 * @summary Les membres d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    suspendedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
    manageable: /*#__PURE__*/ zod.boolean(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdMembersResponseItem,
  );

/**
 * @summary Le rôle et les permissions de l'acteur
 */
export const GetApiOrganizationsOrganizationIdMeParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMeResponse = /*#__PURE__*/ zod.object({
  permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
});

/**
 * @summary Les membres d'une organization
 */
export const GetApiOrganizationsOrganizationIdMembersParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdMembersResponseItem =
  /*#__PURE__*/ zod.object({
    userId: /*#__PURE__*/ zod.string(),
    roleId: /*#__PURE__*/ zod.uuid(),
    roleName: /*#__PURE__*/ zod.string(),
    suspendedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
    manageable: /*#__PURE__*/ zod.boolean(),
    name: /*#__PURE__*/ zod.string(),
    email: /*#__PURE__*/ zod.email(),
    joinedAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdMembersResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdMembersResponseItem,
);

/**
 * @summary Les rôles d'une organization
 */
export const GetApiOrganizationsOrganizationIdRolesParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const GetApiOrganizationsOrganizationIdRolesResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    name: /*#__PURE__*/ zod.string(),
    scope: /*#__PURE__*/ zod.enum(["organization", "project"]),
    isSystem: /*#__PURE__*/ zod.boolean(),
    assignable: /*#__PURE__*/ zod.boolean(),
    permissions: /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
    holders: /*#__PURE__*/ zod.int(),
  });
export const GetApiOrganizationsOrganizationIdRolesResponse = /*#__PURE__*/ zod.array(
  GetApiOrganizationsOrganizationIdRolesResponseItem,
);

/**
 * @summary Créer un rôle personnalisé
 */
export const PostApiOrganizationsOrganizationIdRolesParams = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
});

export const postApiOrganizationsOrganizationIdRolesBodyOneNameMax = 200;

export const PostApiOrganizationsOrganizationIdRolesBody =
  /*#__PURE__*/ zod.intersection(
    /*#__PURE__*/ zod.object({
      name: /*#__PURE__*/ zod
        .string()
        .check(/*#__PURE__*/ zod.minLength(1))
        .check(
          /*#__PURE__*/ zod.maxLength(
            postApiOrganizationsOrganizationIdRolesBodyOneNameMax,
          ),
        ),
      permissions: /*#__PURE__*/ zod.array(
        /*#__PURE__*/ zod.enum([
          "content.read",
          "content.read_draft",
          "content.write",
          "content.publish",
          "schema.read",
          "schema.write",
          "member.read",
          "member.manage",
          "member.manage_admin",
          "role.manage",
          "apikey.manage",
          "project.create",
          "project.delete",
          "org.settings",
          "org.billing",
          "org.transfer",
          "org.delete",
        ]),
      ),
    }),
    /*#__PURE__*/ zod.object({
      scope: /*#__PURE__*/ zod.enum(["organization", "project"]),
    }),
  );

export const PostApiOrganizationsOrganizationIdRolesResponse = /*#__PURE__*/ zod.object(
  {
    id: /*#__PURE__*/ zod.uuid(),
  },
);

/**
 * @summary Les invitations en attente
 */
export const GetApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.array(GetApiOrganizationsOrganizationIdInvitationsResponseItem);

/**
 * @summary Inviter quelqu'un
 */
export const PostApiOrganizationsOrganizationIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Le catalogue de permissions
 */
export const GetApiPermissionsResponseItem = /*#__PURE__*/ zod.object({
  key: /*#__PURE__*/ zod.string(),
  description: /*#__PURE__*/ zod.string(),
});
export const GetApiPermissionsResponse = /*#__PURE__*/ zod.array(
  GetApiPermissionsResponseItem,
);

/**
 * @summary Modifier un rôle personnalisé
 */
export const PutApiOrganizationsOrganizationIdRolesRoleIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const putApiOrganizationsOrganizationIdRolesRoleIdBodyNameMax = 200;

export const PutApiOrganizationsOrganizationIdRolesRoleIdBody =
  /*#__PURE__*/ zod.object({
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          putApiOrganizationsOrganizationIdRolesRoleIdBodyNameMax,
        ),
      ),
    permissions: /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.enum([
        "content.read",
        "content.read_draft",
        "content.write",
        "content.publish",
        "schema.read",
        "schema.write",
        "member.read",
        "member.manage",
        "member.manage_admin",
        "role.manage",
        "apikey.manage",
        "project.create",
        "project.delete",
        "org.settings",
        "org.billing",
        "org.transfer",
        "org.delete",
      ]),
    ),
  });

export const PutApiOrganizationsOrganizationIdRolesRoleIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Supprimer un rôle personnalisé
 */
export const DeleteApiOrganizationsOrganizationIdRolesRoleIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdRolesRoleIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Retirer un membre, ou quitter l'organization
 */
export const DeleteApiOrganizationsOrganizationIdMembersUserIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const DeleteApiOrganizationsOrganizationIdMembersUserIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Suspendre ou réactiver une adhésion
 */
export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionBody =
  /*#__PURE__*/ zod.object({
    suspended: /*#__PURE__*/ zod.boolean(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdSuspensionResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Changer le rôle d'un membre
 */
export const PutApiOrganizationsOrganizationIdMembersUserIdRoleParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdRoleBody =
  /*#__PURE__*/ zod.object({
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PutApiOrganizationsOrganizationIdMembersUserIdRoleResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Retirer un membre d'un projet, ou le quitter
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Suspendre ou réactiver une adhésion à un projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionBody =
  /*#__PURE__*/ zod.object({
    suspended: /*#__PURE__*/ zod.boolean(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdSuspensionResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Changer le rôle d'un membre de projet
 */
export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    userId: /*#__PURE__*/ zod.string(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleBody =
  /*#__PURE__*/ zod.object({
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PutApiOrganizationsOrganizationIdProjectsProjectIdMembersUserIdRoleResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Les clés API d'un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    kind: /*#__PURE__*/ zod.enum(["public", "preview", "secret"]),
    name: /*#__PURE__*/ zod.string(),
    token: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
    hint: /*#__PURE__*/ zod.string(),
    revokedAt: /*#__PURE__*/ zod.nullable(
      /*#__PURE__*/ zod.iso.datetime({ offset: true }),
    ),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponseItem,
  );

/**
 * @summary Créer une clé API
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const postApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBodyNameMax = 200;

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBody =
  /*#__PURE__*/ zod.object({
    kind: /*#__PURE__*/ zod.enum(["public", "preview", "secret"]),
    name: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1))
      .check(
        /*#__PURE__*/ zod.maxLength(
          postApiOrganizationsOrganizationIdProjectsProjectIdApiKeysBodyNameMax,
        ),
      ),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    token: /*#__PURE__*/ zod.string(),
  });

/**
 * @summary Révoquer une clé API
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdRevokeParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    apiKeyId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdRevokeResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Supprimer une clé API révoquée
 */
export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
    apiKeyId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdProjectsProjectIdApiKeysApiKeyIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Les invitations en attente sur un projet
 */
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
    email: /*#__PURE__*/ zod.email(),
    roleName: /*#__PURE__*/ zod.string(),
    expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
  });
export const GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.array(
    GetApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponseItem,
  );

/**
 * @summary Inviter quelqu'un sur un projet
 */
export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    projectId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsBody =
  /*#__PURE__*/ zod.object({
    email: /*#__PURE__*/ zod.email(),
    roleId: /*#__PURE__*/ zod.uuid(),
  });

export const PostApiOrganizationsOrganizationIdProjectsProjectIdInvitationsResponse =
  /*#__PURE__*/ zod.object({
    id: /*#__PURE__*/ zod.uuid(),
  });

/**
 * @summary Annuler une invitation
 */
export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdParams =
  /*#__PURE__*/ zod.object({
    organizationId: /*#__PURE__*/ zod.uuid(),
    invitationId: /*#__PURE__*/ zod.uuid(),
  });

export const DeleteApiOrganizationsOrganizationIdInvitationsInvitationIdResponse =
  /*#__PURE__*/ zod.void();

/**
 * @summary Décrire une invitation
 */

export const GetApiInvitationsTokenParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const GetApiInvitationsTokenResponse = /*#__PURE__*/ zod.object({
  email: /*#__PURE__*/ zod.email(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  hasAccount: /*#__PURE__*/ zod.boolean(),
});

/**
 * @summary Accepter une invitation
 */

export const PostApiInvitationsTokenAcceptParams = /*#__PURE__*/ zod.object({
  token: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
});

export const PostApiInvitationsTokenAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});

/**
 * @summary Les invitations reçues
 */
export const GetApiInboxResponseItem = /*#__PURE__*/ zod.object({
  id: /*#__PURE__*/ zod.uuid(),
  organizationName: /*#__PURE__*/ zod.string(),
  projectName: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.string()),
  roleName: /*#__PURE__*/ zod.string(),
  expiresAt: /*#__PURE__*/ zod.iso.datetime({ offset: true }),
});
export const GetApiInboxResponse = /*#__PURE__*/ zod.array(GetApiInboxResponseItem);

/**
 * @summary Accepter une invitation reçue
 */
export const PostApiInboxInvitationIdAcceptParams = /*#__PURE__*/ zod.object({
  invitationId: /*#__PURE__*/ zod.uuid(),
});

export const PostApiInboxInvitationIdAcceptResponse = /*#__PURE__*/ zod.object({
  organizationId: /*#__PURE__*/ zod.uuid(),
  projectId: /*#__PURE__*/ zod.nullable(/*#__PURE__*/ zod.uuid()),
});
